friendlier output
I am now getting: "The cache has no package named 'bbb'"

instead of:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 179, in __getitem__
    return self._weakref[key]
  File "/usr/lib/python3.2/weakref.py", line 69, in __getitem__
    o = self.data[key]()
KeyError: 'bbb'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wena/src/wajig/src/util.py", line 103, in package_exists
    cache[package]
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 186, in __getitem__
    raise KeyError('The cache has no package named %r' % key)
KeyError: "The cache has no package named 'bbb'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wena/src/wajig/src/wajig.py", line 853, in <module>
    main()
  File "/home/wena/src/wajig/src/wajig.py", line 166, in main
    select_command(command, args, result.verbose)
  File "/home/wena/src/wajig/src/wajig.py", line 205, in select_command
    commands.changelog(args, verbose)
  File "/home/wena/src/wajig/src/commands.py", line 762, in changelog
    util.package_exists(package_name)
  File "/home/wena/src/wajig/src/util.py", line 107, in package_exists
    print(e[0])
TypeError: 'KeyError' object is not subscriptable